# Generated by Django 2.2.6 on 2019-10-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
