version: "3.7"

services:
    backend:
        build: ./backend
        command: bash -c "cd ./backend && python ./setup.py build_ext --inplace && python ./main.py"
        volumes:
          - .:/backend
        ports:
          - "8000:8000"