version: "3.7"

services:
    db-postgres:
        image: postgres
        container_name: db-postgres
        ports:
            - "5432:5432"
    db-mongo:
        image: mongo
        container_name: db-mongo
        ports:
            - "27017:27017"
    backend:
        image: backend
        container_name: backend
        build: ./backend
        #command: bash -c "cd ./backend/lessonplans/algorithm && python ./setup.py build_ext --inplace && cd ../../ && python ./main.py"
        command: bash -c "./wait-for-it.sh -t 10 db-postgres:5432 -- bash -c 'cd ./backend/lessonplans/algorithm && python ./setup.py build_ext --inplace && cd ../../ && python ./manage.py migrate && python ./manage.py runserver 0.0.0.0:8000'"
        #DANGEROUS!!! bellow command makes migrations everytime
        #command: bash -c "./wait-for-it.sh -t 10 db-postgres:5432 -- bash -c 'cd ./backend/lessonplans/algorithm && python ./setup.py build_ext --inplace && cd ../../ && python ./manage.py makemigrations && python ./manage.py migrate && python ./manage.py runserver 0.0.0.0:8000'"
        
        #command: ["./wait-for-it.sh", "database:5432"]
        #command: ["./wait-for-it.sh", "database-norel:27017"]
        #command: bash -c "cd ./backend && python manage.py migrate"
        #command: bash -c "cd ./backend/lessonplans/algorithm && python ./setup.py build_ext --inplace"
        #command: bash -c "cd ./backend && python ./manage.py runserver 0.0.0.0:8000"
        #command: bash -c "cd ./backend && python manage.py migrate && python ./manage.py runserver 0.0.0.0:8000"
        #command: bash -c "cd ./backend/lessonplans/algorithm && python ./setup.py build_ext --inplace && cd ../ && python ./main.py"
        volumes:
          - .:/backend
        ports:
          - "8000:8000"
        depends_on:
          - db-postgres
          - db-mongo
        #command: bash -c "cd ./backend && python ./main.py"
