version: "3.7"

services:
    database:
        image: postgres
    database-norel:
        image: mongo
        ports:
            - "27017:27017"
    backend:
        image: backend
        build: ./backend
        command: bash -c "cd ./backend/lessonplans/algorithm && python ./setup.py build_ext --inplace && cd ../../ && python ./manage.py migrate && python ./manage.py runserver 0.0.0.0:8000"
        #command: ["./wait-for-it.sh", "database:5432"]
        #command: ["./wait-for-it.sh", "database-norel:27017"]
        #command: bash -c "cd ./backend && python manage.py migrate"
        #command: bash -c "cd ./backend/lessonplans/algorithm && python ./setup.py build_ext --inplace"
        #command: bash -c "cd ./backend && python ./manage.py runserver 0.0.0.0:8000"
        #command: bash -c "cd ./backend && python manage.py migrate && python ./manage.py runserver 0.0.0.0:8000"
        #command: bash -c "cd ./backend/algorithm && python ./setup.py build_ext --inplace && cd ../ && python ./main.py"
        volumes:
          - .:/backend
        ports:
          - "8000:8000"
        depends_on:
          - database
          - database-norel
        #command: bash -c "cd ./backend && python ./main.py"